//! Raw FFI bindings from `bindgen` and `autocxx`.
#![allow(clippy::all)]
use autocxx::prelude::*;
pub use ffi_autocxx::*;

cpp::cpp! {{
    #include "pxr_sys/pxr.h"
}}

include_cpp! {
    #include "pxr_sys/pxr.h"

    // Generate unsafe bindings in `ffi_autocxx` module
    name!(ffi_autocxx)
    safety!(unsafe)

    // Specify & rename concrete types
    concrete!("pxrInternal_v0_22__pxrReserved__::TfWeakPtr<pxrInternal_v0_22__pxrReserved__::UsdStage>", UsdStageHandle)

    // Declare external types from manual bindings
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfCleanupEnabler", crate::ffi::pxr::SdfCleanupEnabler)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::SdfValueTypeNames", crate::ffi::pxr::SdfValueTypeNames)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStageCacheContext", crate::ffi::pxr::UsdStageCacheContext)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::UsdStageWeakPtr", crate::ffi::pxr::UsdStageWeakPtr)
    extern_cpp_type!("pxrInternal_v0_22__pxrReserved__::VtDictionary", crate::ffi::pxr::VtDictionary)

    // Generate cxx bindings
    generate!("pxrInternal_v0_22__pxrReserved__::GfBBox3d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfCamera")
    generate!("pxrInternal_v0_22__pxrReserved__::GfDualQuatd")
    generate!("pxrInternal_v0_22__pxrReserved__::GfDualQuatf")
    generate!("pxrInternal_v0_22__pxrReserved__::GfDualQuath")
    generate!("pxrInternal_v0_22__pxrReserved__::GfFrustum")
    generate!("pxrInternal_v0_22__pxrReserved__::GfInterval")
    generate!("pxrInternal_v0_22__pxrReserved__::GfLine")
    generate!("pxrInternal_v0_22__pxrReserved__::GfLine2d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfLineSeg")
    generate!("pxrInternal_v0_22__pxrReserved__::GfLineSeg2d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfMatrix2d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfMatrix2f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfMatrix3d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfMatrix3f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfMatrix4d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfMatrix4f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfPlane")
    generate!("pxrInternal_v0_22__pxrReserved__::GfQuatd")
    generate!("pxrInternal_v0_22__pxrReserved__::GfQuaternion")
    generate!("pxrInternal_v0_22__pxrReserved__::GfQuatf")
    generate!("pxrInternal_v0_22__pxrReserved__::GfQuath")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRange1d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRange1f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRange2d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRange2f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRange3d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRange3f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRay")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRect2i")
    generate!("pxrInternal_v0_22__pxrReserved__::GfRotation")
    generate!("pxrInternal_v0_22__pxrReserved__::GfSize2")
    generate!("pxrInternal_v0_22__pxrReserved__::GfSize3")
    generate!("pxrInternal_v0_22__pxrReserved__::GfTransform")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec2d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec2f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec2h")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec2i")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec3d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec3f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec3h")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec3i")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec4d")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec4f")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec4h")
    generate!("pxrInternal_v0_22__pxrReserved__::GfVec4i")
    // generate!("pxrInternal_v0_22__pxrReserved__::GfMultiInterval")

    generate!("pxrInternal_v0_22__pxrReserved__::SdfAttributeSpec")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfFileFormat")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfLayer")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfLayerHandle")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfLayerOffset")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfLayerRefPtr")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfPath")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfPropertySpec")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfReference")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfRelationshipSpec")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfSite")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfSpec")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfTimeCode")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfValueTypeName")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfVariantSpec")
    generate!("pxrInternal_v0_22__pxrReserved__::SdfSchemaBase")
    // generate!("pxrInternal_v0_22__pxrReserved__::SdfAssetPath")
    // generate!("pxrInternal_v0_22__pxrReserved__::SdfPrimSpec")
    // generate!("pxrInternal_v0_22__pxrReserved__::SdfVariantSetSpec")

    generate!("pxrInternal_v0_22__pxrReserved__::TfEnum")
    generate!("pxrInternal_v0_22__pxrReserved__::TfSingleton")
    generate!("pxrInternal_v0_22__pxrReserved__::TfToken")
    generate!("pxrInternal_v0_22__pxrReserved__::TfType")
    generate!("pxrInternal_v0_22__pxrReserved__::TfTypeInfoMap")

    generate_pod!("pxrInternal_v0_22__pxrReserved__::Usd_PrimFlagsPredicate")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdAPISchemaBase")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdAttribute")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdCollectionAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdInherits")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdNotice")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdObject")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPayloads")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrim")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimCompositionQuery")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimCompositionQueryArc")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimDefinition")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimRange_iterator")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimRange")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimSiblingRange")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimSubtreeRange")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPrimTypeInfo")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdProcTokensType")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdProperty")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdReferences")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdRelationship")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdRenderTokensType")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdResolveInfo")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdResolveTarget")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdSchemaBase")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdStage")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdStageCache")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdStageRefPtr")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdTimeCode")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdTyped")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdVariantSet")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdVariantSets")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdZipFile")

    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomBasisCurves")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomBBoxCache")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomCamera")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomCapsule")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomCone")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomConstraintTarget")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomCube")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomCylinder")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomGprim")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomImageable")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomMesh")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomNurbsCurves")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomNurbsPatch")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomPointInstancer")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomPoints")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomPrimvar")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomSphere")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomTokensType")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomXform")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomXformable")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomXformCache")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdGeomXformOp")

    generate!("pxrInternal_v0_22__pxrReserved__::UsdHydraTokensType")

    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsArticulationRootAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsCollisionAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsCollisionGroup")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsDistanceJoint")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsDriveAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsFilteredPairsAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsFixedJoint")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsJoint")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsLimitAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMassAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMassUnits")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMaterialAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsMeshCollisionAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsPrismaticJoint")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsRevoluteJoint")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsRigidBodyAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsScene")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsSphericalJoint")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsTokens")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsTokensType")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdPhysicsTokensType")

    generate!("pxrInternal_v0_22__pxrReserved__::UsdShadeInput")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdShadeMaterial")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdShadeMaterialBindingAPI")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdShadeOutput")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdShadeShader")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdShadeUtils")

    generate!("pxrInternal_v0_22__pxrReserved__::UsdUtilsRegisteredVariantSet")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdUtilsSparseAttrValueWriter")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdUtilsSparseValueWriter")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdUtilsStageCache")
    generate!("pxrInternal_v0_22__pxrReserved__::UsdUtilsTimeCodeRange")

    generate!("pxrInternal_v0_22__pxrReserved__::VtValue")
}
